### ISSUE TITLE
sphinx build breaks on fresh install

### ISSUE THREAD

**Issue by polvi** [dinoboff/github-tools#8]
Hello!

I was trying to get everything setup for the first time, and the sphinx build would break on:

Built html doc from docs/source to docs/build/html
sphinx-build -d docs/build/doctrees -b html docs/source docs/build/html
Exception occurred:
  File "/Users/polvi/Code/foomodule/docs/source/conf.py", line 8, in <module>
    import foomodule
ImportError: No module named foomodule
The full traceback has been saved in /var/folders/gV/gVCXo93WGwiTkiMdXbXpK++++TM/-Tmp-/sphinx-err-FXM2bs.log, if you want to report the issue to the author.
Please also report this if it was a user error, so that a better error message can be provided next time.
Send reports to sphinx-dev@googlegroups.com. Thanks!

Applying this patch helped:

diff --git a/docs/source/conf.py b/docs/source/conf.py
index 756e419..717cb7f 100644
--- a/docs/source/conf.py
+++ b/docs/source/conf.py
@@ -4,6 +4,7 @@ import sys, os

 _here = os.path.dirname(os.path.abspath(__file__))
 sys.path.insert(0, os.path.join(_here, '../../../src'))
+sys.path.insert(0, os.path.join(_here, '../../src'))

 import txrackspace
 version = txrackspace.VERSION

I also had to create the directory "/Users/polvi/Code/txrackspace/docs/source/_static". After all that, using "paver gh_pages_create gh_pages_build" worked. github_tools-0.1.7-py2.5

**Comment by dinoboff** [comment]
Hi,

It is probably related to issue #1. I have since change docs/source/conf because of issue #6 (It was a bad idea to import the package meta-data form the main package).

Here is the result for docs/source/conf.py
http://github.com/dinoboff/github-tools/blob/c75c1cd9a03bcfcfb0f9201a5cf7ce2990b80233/src/github/tools/tmpl/gh/docs/source/conf.py_tmpl

I will check if `_static` and `_templates` are still missing for v0.1.7
